# Generated by Django 5.0 on 2023-12-28 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=20)),
                ('pet_image', models.ImageField(max_length=2856, upload_to='')),
                ('pet_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furn_name', models.CharField(max_length=130)),
                ('furn_image', models.ImageField(null=True, upload_to='')),
                ('furn_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gadget_name', models.CharField(max_length=30)),
                ('gadget_image', models.ImageField(upload_to='')),
                ('gadget_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_category', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Attire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attire_name', models.CharField(max_length=20)),
                ('attire_image', models.ImageField(max_length=2856, upload_to='')),
                ('attire_price', models.IntegerField()),
                ('attire_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='druinteriors.fashion')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=20)),
                ('phone_image', models.ImageField(max_length=2856, upload_to='')),
                ('phone_price', models.IntegerField()),
                ('phone_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='druinteriors.phonecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_name', models.CharField(max_length=20)),
                ('shirt_image', models.ImageField(max_length=2856, upload_to='')),
                ('shirt_price', models.IntegerField()),
                ('shirt_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='druinteriors.fashion')),
            ],
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_name', models.CharField(max_length=20)),
                ('sneaker_image', models.ImageField(max_length=2856, upload_to='')),
                ('sneaker_price', models.IntegerField()),
                ('sneaker_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='druinteriors.fashion')),
            ],
        ),
        migrations.CreateModel(
            name='Trouser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trouser_name', models.CharField(max_length=20)),
                ('trouser_image', models.ImageField(max_length=2856, upload_to='')),
                ('trouser_price', models.IntegerField()),
                ('trouser_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='druinteriors.fashion')),
            ],
        ),
    ]
